<Gpt>:
    MDBoxLayout:
        orientation: 'vertical'
        MDBoxLayout:
            size_hint: 1, 1.5
            MDScreen:
                md_bg_color: 'white'
                ScrollView:
                    id: scroll_view
                    MDLabel:
                        id: label_id
                        text: ''
                        size_hint_y: None
                        height: self.texture_size[1]
    
        MDBoxLayout:
            MDScreen:
                md_bg_color: 'white'
                ScrollView:
                    id: scroll_view
                    MDTextField:
                        id: user_input
                        multiline: True
                        text:'écrire ici'
                

                BoxLayout:
                    id: button_layout
                    size_hint_y: None
                    height: dp(48)

                    MDIconButton:
                        icon: "send"
                        on_release:root.on_send_message()